/**
 * Pre-compiled regex patterns for the Luau TextMate grammar.
 * Generated by scripts/compile-grammar-regexes.js
 * 
 * DO NOT EDIT MANUALLY
 */

// Map of Oniguruma pattern string -> [source, flags] tuple
// null means the pattern couldn't be compiled (will fallback gracefully)
export const compiledPatterns: Record<string, [string, string] | null> = {
  "\\b(?:(local)\\s+)?(function)\\b(?![,:])": [
    "\\b(?:(local)\\p{space}+)?(function)\\b(?![\\,\\:])",
    "dgv"
  ],
  "(?<=[\\)\\-{}\\[\\]\"'])": [
    "(?<=[\\)\\-\\{\\}\\[\\]\"'])",
    "dgv"
  ],
  "(\\()": [
    "(\\()",
    "dgv"
  ],
  "(\\))": [
    "(\\))",
    "dgv"
  ],
  "\\.\\.\\.": [
    "\\.\\.\\.",
    "dgv"
  ],
  "[a-zA-Z_][a-zA-Z0-9_]*": [
    "[a-zA-Z_][a-zA-Z0-9_]*",
    "dgv"
  ],
  ",": [
    ",",
    "dgv"
  ],
  ":": [
    ":",
    "dgv"
  ],
  "(?=[\\),])": [
    "(?=[\\)\\,])",
    "dgv"
  ],
  "\\b(__add|__call|__concat|__div|__eq|__index|__le|__len|__lt|__metatable|__mod|__mode|__mul|__newindex|__pow|__sub|__tostring|__unm|__iter|__idiv)\\b": [
    "\\b(__add|__call|__concat|__div|__eq|__index|__le|__len|__lt|__metatable|__mod|__mode|__mul|__newindex|__pow|__sub|__tostring|__unm|__iter|__idiv)\\b",
    "dgv"
  ],
  "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b": [
    "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b",
    "dgv"
  ],
  "\\b(local)\\b": [
    "\\b(local)\\b",
    "dgv"
  ],
  "(?=\\s*do\\b|\\s*[=;]|\\s*$)": [
    "(?=\\p{space}*do\\b|\\p{space}*[\\=\\;]|\\p{space}*(?=\\n?$))",
    "dgv"
  ],
  "(:)": [
    "(:)",
    "dgv"
  ],
  "(?=\\s*do\\b|\\s*[=;,]|\\s*$)": [
    "(?=\\p{space}*do\\b|\\p{space}*[\\=\\;\\,]|\\p{space}*(?=\\n?$))",
    "dgv"
  ],
  "\\b([A-Z_][A-Z0-9_]*)\\b": [
    "\\b([A-Z_][A-Z0-9_]*)\\b",
    "dgv"
  ],
  "\\b(for)\\b": [
    "\\b(for)\\b",
    "dgv"
  ],
  "\\b(in)\\b|(=)": [
    "\\b(in)\\b|(=)",
    "dgv"
  ],
  "(?=\\s*in\\b|\\s*[=,]|\\s*$)": [
    "(?=\\p{space}*in\\b|\\p{space}*[\\=\\,]|\\p{space}*(?=\\n?$))",
    "dgv"
  ],
  "\\A(#!).*$\\n?": [
    "^(#!)[^\\n]*(?=\\n?$)\\n?",
    "dgv"
  ],
  "\\\\[abfnrtvz'\"`{\\\\]": [
    "\\\\[abfnrtvz'\"\\`\\{\\\\]",
    "dgv"
  ],
  "\\\\\\d{1,3}": [
    "\\\\\\p{Nd}{1,3}",
    "dgv"
  ],
  "\\\\x[0-9a-fA-F]{2}": [
    "\\\\x[0-9a-fA-F]{2}",
    "dgv"
  ],
  "\\\\u\\{[0-9a-fA-F]*\\}": [
    "\\\\u\\{[0-9a-fA-F]*\\}",
    "dgv"
  ],
  "\\\\$": [
    "\\\\(?=\\n?$)",
    "dgv"
  ],
  "\\b0_*[xX]_*[\\da-fA-F_]*(?:[eE][\\+\\-]?_*\\d[\\d_]*(?:\\.[\\d_]*)?)?": [
    "\\b0_*[xX]_*[\\p{Nd}a-fA-F_]*(?:[eE][\\+\\-]?_*\\p{Nd}[\\p{Nd}_]*(?:\\.[\\p{Nd}_]*)?)?",
    "dgv"
  ],
  "\\b0_*[bB][01_]+(?:[eE][\\+\\-]?_*\\d[\\d_]*(?:\\.[\\d_]*)?)?": [
    "\\b0_*[bB][01_]+(?:[eE][\\+\\-]?_*\\p{Nd}[\\p{Nd}_]*(?:\\.[\\p{Nd}_]*)?)?",
    "dgv"
  ],
  "(?:\\d[\\d_]*(?:\\.[\\d_]*)?|\\.\\d[\\d_]*)(?:[eE][\\+\\-]?_*\\d[\\d_]*(?:\\.[\\d_]*)?)?": [
    "(?:\\p{Nd}[\\p{Nd}_]*(?:\\.[\\p{Nd}_]*)?|\\.\\p{Nd}[\\p{Nd}_]*)(?:[eE][\\+\\-]?_*\\p{Nd}[\\p{Nd}_]*(?:\\.[\\p{Nd}_]*)?)?",
    "dgv"
  ],
  "\"": [
    "\"",
    "dgv"
  ],
  "'": [
    "'",
    "dgv"
  ],
  "\\[(=*)\\[": [
    "\\[(=*)\\[",
    "dgv"
  ],
  "\\]\\1\\]": [
    "\\]\\1\\]()",
    "dgv"
  ],
  "`": [
    "`",
    "dgv"
  ],
  "\\{": [
    "\\{",
    "dgv"
  ],
  "\\}": [
    "\\}",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(assert|collectgarbage|error|gcinfo|getfenv|getmetatable|ipairs|loadstring|newproxy|next|pairs|pcall|print|rawequal|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|typeof|unpack|xpcall)\\b": [
    "(?<![^\\.]\\.|:)\\b(assert|collectgarbage|error|gcinfo|getfenv|getmetatable|ipairs|loadstring|newproxy|next|pairs|pcall|print|rawequal|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|typeof|unpack|xpcall)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(_G|_VERSION)\\b": [
    "(?<![^\\.]\\.|:)\\b(_G|_VERSION)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(bit32\\.(?:arshift|band|bnot|bor|btest|bxor|extract|lrotate|lshift|replace|rrotate|rshift|countlz|countrz|byteswap)|coroutine\\.(?:create|isyieldable|resume|running|status|wrap|yield|close)|debug\\.(?:info|loadmodule|profilebegin|profileend|traceback)|math\\.(?:abs|acos|asin|atan|atan2|ceil|clamp|cos|cosh|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|noise|pow|rad|random|randomseed|round|sign|sin|sinh|sqrt|tan|tanh)|os\\.(?:clock|date|difftime|time)|string\\.(?:byte|char|find|format|gmatch|gsub|len|lower|match|pack|packsize|rep|reverse|split|sub|unpack|upper)|table\\.(?:concat|create|find|foreach|foreachi|getn|insert|maxn|move|pack|remove|sort|unpack|clear|freeze|isfrozen|clone)|task\\.(?:spawn|synchronize|desynchronize|wait|defer|delay)|utf8\\.(?:char|codepoint|codes|graphemes|len|nfcnormalize|nfdnormalize|offset)|buffer\\.(?:create|fromstring|tostring|len|readi8|readu8|readi16|readu16|readi32|readu32|readf32|readf64|writei8|writeu8|writei16|writeu16|writei32|writeu32|writef32|writef64|readstring|writestring|copy|fill))\\b": [
    "(?<![^\\.]\\.|:)\\b(bit32\\.(?:arshift|band|bnot|bor|btest|bxor|extract|lrotate|lshift|replace|rrotate|rshift|countlz|countrz|byteswap)|coroutine\\.(?:create|isyieldable|resume|running|status|wrap|yield|close)|debug\\.(?:info|loadmodule|profilebegin|profileend|traceback)|math\\.(?:abs|acos|asin|atan|atan2|ceil|clamp|cos|cosh|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|noise|pow|rad|random|randomseed|round|sign|sin|sinh|sqrt|tan|tanh)|os\\.(?:clock|date|difftime|time)|string\\.(?:byte|char|find|format|gmatch|gsub|len|lower|match|pack|packsize|rep|reverse|split|sub|unpack|upper)|table\\.(?:concat|create|find|foreach|foreachi|getn|insert|maxn|move|pack|remove|sort|unpack|clear|freeze|isfrozen|clone)|task\\.(?:spawn|synchronize|desynchronize|wait|defer|delay)|utf8\\.(?:char|codepoint|codes|graphemes|len|nfcnormalize|nfdnormalize|offset)|buffer\\.(?:create|fromstring|tostring|len|readi8|readu8|readi16|readu16|readi32|readu32|readf32|readf64|writei8|writeu8|writei16|writeu16|writei32|writeu32|writef32|writef64|readstring|writestring|copy|fill))\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(bit32|buffer|coroutine|debug|math(\\.(huge|pi))?|os|string|table|task|utf8(\\.charpattern)?)\\b": [
    "(?<![^\\.]\\.|:)\\b(bit32|buffer|coroutine|debug|math(\\.(huge|pi))?|os|string|table|task|utf8(\\.charpattern)?)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(delay|DebuggerManager|elapsedTime|PluginManager|printidentity|settings|spawn|stats|tick|time|UserSettings|version|wait|warn)\\b": [
    "(?<![^\\.]\\.|:)\\b(delay|DebuggerManager|elapsedTime|PluginManager|printidentity|settings|spawn|stats|tick|time|UserSettings|version|wait|warn)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(game|plugin|shared|script|workspace|Enum(?:\\.\\w+){0,2})\\b": [
    "(?<![^\\.]\\.|:)\\b(game|plugin|shared|script|workspace|Enum(?:\\.[\\p{L}\\p{M}\\p{N}\\p{Pc}]+){0,2})\\b",
    "dgv"
  ],
  "\\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|in|continue)\\b": [
    "\\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|in|continue)\\b",
    "dgv"
  ],
  "\\b(function)\\b(?![,:])": [
    "\\b(function)\\b(?![\\,\\:])",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(self)\\b": [
    "(?<![^\\.]\\.|:)\\b(self)\\b",
    "dgv"
  ],
  "\\b(and|or|not)\\b": [
    "\\b(and|or|not)\\b",
    "dgv"
  ],
  "(?<=[^.]\\.|:)\\b(__add|__call|__concat|__div|__eq|__index|__le|__len|__lt|__metatable|__mod|__mode|__mul|__newindex|__pow|__sub|__tostring|__unm)\\b": [
    "(?<=[^\\.]\\.|:)\\b(__add|__call|__concat|__div|__eq|__index|__le|__len|__lt|__metatable|__mod|__mode|__mul|__newindex|__pow|__sub|__tostring|__unm)\\b",
    "dgv"
  ],
  "(?<![.])\\.{3}(?!\\.)": [
    "(?<![\\.])\\.{3}(?!\\.)",
    "dgv"
  ],
  "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(?=\\s*(?:[({\"']|\\[\\[))": [
    "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(?=\\p{space}*(?:[\\(\\{\"']|\\[\\[))",
    "dgv"
  ],
  "(?<=[^.]\\.|:)\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b": [
    "(?<=[^\\.]\\.|:)\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b",
    "dgv"
  ],
  "==|~=|!=|<=?|>=?": [
    "==|~=|!=|<=?|>=?",
    "dgv"
  ],
  "\\+=|-=|/=|//=|\\*=|%=|\\^=|\\.\\.=|=": [
    "\\+=|-=|\\/=|\\/\\/=|\\*=|%=|\\^=|\\.\\.=|=",
    "dgv"
  ],
  "\\+|-|%|\\*|\\/\\/|\\/|\\^": [
    "\\+|-|%|\\*|\\/\\/|\\/|\\^",
    "dgv"
  ],
  "#|(?<!\\.)\\.{2}(?!\\.)": [
    "#|(?<!\\.)\\.{2}(?!\\.)",
    "dgv"
  ],
  "(\\{)": [
    "(\\{)",
    "dgv"
  ],
  "(\\})": [
    "(\\})",
    "dgv"
  ],
  "[,;]": [
    "[\\,\\;]",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(false)\\b": [
    "(?<![^\\.]\\.|:)\\b(false)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(true)\\b": [
    "(?<![^\\.]\\.|:)\\b(true)\\b",
    "dgv"
  ],
  "(?<![^.]\\.|:)\\b(nil(?!:))\\b": [
    "(?<![^\\.]\\.|:)\\b(nil(?!:))\\b",
    "dgv"
  ],
  "--\\[(=*)\\[": [
    "--\\[(=*)\\[",
    "dgv"
  ],
  "(```luau?)\\s+": [
    "(```luau?)\\p{space}+",
    "dgv"
  ],
  "(```)": [
    "(```)",
    "dgv"
  ],
  "---": [
    "---",
    "dgv"
  ],
  "\\n": [
    "\\n",
    "dgv"
  ],
  "--": [
    "--",
    "dgv"
  ],
  "@\\w+": [
    "@[\\p{L}\\p{M}\\p{N}\\p{Pc}]+",
    "dgv"
  ],
  "((?<=[\\s*!\\/])[\\\\@]param)(?:\\s)+(\\b\\w+\\b)": [
    "((?<=[\\p{space}\\*\\!\\/])[\\\\\\@]param)(?:\\p{space})+(\\b[\\p{L}\\p{M}\\p{N}\\p{Pc}]+\\b)",
    "dgv"
  ],
  "(<)": [
    "(<)",
    "dgv"
  ],
  "(>)": [
    "(>)",
    "dgv"
  ],
  "=": [
    "=",
    "dgv"
  ],
  "^\\b(?:(export)\\s+)?(type)\\s+(function)\\b": [
    "^\\b(?:(export)\\p{space}+)?(type)\\p{space}+(function)\\b",
    "dgv"
  ],
  "^\\b(?:(export)\\s+)?(type)\\b": [
    "^\\b(?:(export)\\p{space}+)?(type)\\b",
    "dgv"
  ],
  "(?=\\s*$)|(?=\\s*;)": [
    "(?=\\p{space}*(?=\\n?$))|(?=\\p{space}*;)",
    "dgv"
  ],
  ":(?!\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(?=\\s*(?:[({\"']|\\[\\[)))": [
    ":(?!\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(?=\\p{space}*(?:[\\(\\{\"']|\\[\\[)))",
    "dgv"
  ],
  "(?<=\\))(?!\\s*->)|=|;|$|(?=\\breturn\\b)|(?=\\bend\\b)": [
    "(?<=\\))(?!\\p{space}*->)|=|;|(?=\\n?$)|(?=\\breturn\\b)|(?=\\bend\\b)",
    "dgv"
  ],
  "(::)": [
    "(::)",
    "dgv"
  ],
  "(?=^|[;),}\\]:?\\-\\+\\>](?!\\s*[&\\|])|$|\\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|in|continue)\\b)": [
    "(?=^|[\\;\\)\\,\\}\\]\\:\\?\\-\\+\\>](?!\\p{space}*[\\&\\|])|(?=\\n?$)|\\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|in|continue)\\b)",
    "dgv"
  ],
  "\\?|\\&|\\|": [
    "\\?|&|\\|",
    "dgv"
  ],
  "->": [
    "->",
    "dgv"
  ],
  "\\b(false)\\b": [
    "\\b(false)\\b",
    "dgv"
  ],
  "\\b(true)\\b": [
    "\\b(true)\\b",
    "dgv"
  ],
  "\\b(nil|string|number|boolean|thread|userdata|symbol|vector|buffer|unknown|never|any)\\b": [
    "\\b(nil|string|number|boolean|thread|userdata|symbol|vector|buffer|unknown|never|any)\\b",
    "dgv"
  ],
  "\\b(typeof)\\b(\\()": [
    "\\b(typeof)\\b(\\()",
    "dgv"
  ],
  "\\[": [
    "\\[",
    "dgv"
  ],
  "\\]": [
    "\\]",
    "dgv"
  ],
  "\\b(?:(read|write)\\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\\b(:)": [
    "\\b(?:(read|write)\\p{space}+)?([a-zA-Z_][a-zA-Z0-9_]*)\\b(:)",
    "dgv"
  ],
  "\\(": [
    "\\(",
    "dgv"
  ],
  "\\)": [
    "\\)",
    "dgv"
  ],
  "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(:)": [
    "\\b([a-zA-Z_][a-zA-Z0-9_]*)\\b(:)",
    "dgv"
  ],
  "(@)([a-zA-Z_][a-zA-Z0-9_]*)": [
    "(@)([a-zA-Z_][a-zA-Z0-9_]*)",
    "dgv"
  ]
};

// Total patterns: 90
// Successfully compiled: 90
// Failed: 0
