// @ts-nocheck
async function createLuauModule(moduleArg={}){var Module=moduleArg;var aa=!!globalThis.WorkerGlobalScope,ba="./this.program",ca=import.meta.url,m="",da,n;if(globalThis.window||aa){try{m=(new URL(".",ca)).href}catch{}aa&&(n=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ea=console.log.bind(console),p=console.error.bind(console),q=!1,r;class v{}class x extends v{constructor(a){super();
this.Ya=a}}function fa(){if(!z?.buffer?.resizable){var a=B.buffer;z=new Int8Array(a);C=new Int16Array(a);E=new Uint8Array(a);new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);ha=new Float32Array(a);ia=new Float64Array(a);H=new BigInt64Array(a);new BigUint64Array(a)}}function ja(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),ka.push(...a));for(a=ka;a.length>0;)a.shift()(Module)}function la(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),ma.push(...a));for(a=ma;a.length>
0;)a.shift()(Module)}function I(a){Module.onAbort?.(a);a=`Aborted(${a})`;p(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){try{var b=await da(a);return new Uint8Array(b)}catch{}if(n)a=n(a);else throw"both async and sync fetching of the wasm failed";return a}async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function qa(a){var b=
na;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var C,F,H,z,ha,ia,G,E,ma=[],ka=[],J=!0,K=[],N=0,O=null;class P{constructor(a){this.Ya=a;this.Xa=a-24}init(a,b){G[this.Xa+16>>2]=0;G[this.Xa+4>>2]=a;G[this.Xa+8>>2]=b}}var ta=a=>{var b=
O?.Ya;if(!b)return Q(0),0;var c=new P(b);G[c.Xa+16>>2]=b;var d=G[c.Xa+4>>2];if(!d)return Q(0),b;for(var e of a){if(e===0||e===d)break;if(sa(e,d,c.Xa+16))return Q(e),b}Q(d);return b},ua=0,va=[0,31,60,91,121,152,182,213,244,274,305,335],wa=[0,31,59,90,120,151,181,212,243,273,304,334],xa=globalThis.TextDecoder&&new TextDecoder,ya=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(d-b>16&&a.buffer&&xa)return xa.decode(a.subarray(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&
63;if((c&224)==192)e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=(c&240)==224?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;c<65536?e+=String.fromCharCode(c):(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},R={},za=a=>{if(!(a instanceof ra||a=="unwind"))throw a;},Aa=a=>{r=a;J||ua>0||(Module.onExit?.(a),q=!0);throw new ra(a);},Ba=a=>{if(!q)try{a()}catch(b){za(b)}finally{if(!(J||ua>0))try{r=a=r,Aa(a)}catch(b){za(b)}}},S=(a,b,c)=>{var d=
E;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Ca={},Fa=()=>{if(!Da){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??
"C").replace("-","_")+".UTF-8",_:ba},b;for(b in Ca)Ca[b]===void 0?delete a[b]:a[b]=Ca[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Da=c}return Da},Da,Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Ha=[null,[],[]],Ia=[],T=a=>{var b=Ia[a];b||(Ia[a]=b=Ja.get(a));return b},La=(a,b,c,d)=>{var e={string:k=>{var t=0;if(k!==null&&k!==void 0&&k!==0){t=Ga(k)+1;var u=Ka(t);S(k,u,t);t=u}return t},array:k=>{var t=Ka(k.length);
z.set(k,t);return t}};a=Module["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var l=e[c[h]];l?(g===0&&(g=U()),f[h]=l(d[h])):f[h]=d[h]}c=a(...f);return c=function(k){g!==0&&V(g);return b==="string"?k?ya(E,k):"":b==="boolean"?!!k:k}(c)};Module.noExitRuntime&&(J=Module.noExitRuntime);Module.print&&(ea=Module.print);Module.printErr&&(p=Module.printErr);Module.thisProgram&&(ba=Module.thisProgram);var W=Module.preInit;if(W)for(typeof W=="function"&&(Module.preInit=W=[W]);W.length>0;)W.shift()();Module.ccall=
La;Module.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>f==="number"||f==="boolean");return b!=="string"&&e&&!d?Module["_"+a]:(...f)=>La(a,b,c,f,d)};Module.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":z[a]=b;break;case "i8":z[a]=b;break;case "i16":C[a>>1]=b;break;case "i32":F[a>>2]=b;break;case "i64":H[a>>3]=BigInt(b);break;case "float":ha[a>>2]=b;break;case "double":ia[a>>3]=b;break;case "*":G[a>>2]=b;break;default:I(`invalid type for setValue: ${c}`)}};Module.getValue=function(a,
b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return z[a];case "i8":return z[a];case "i16":return C[a>>1];case "i32":return F[a>>2];case "i64":return H[a>>3];case "float":return ha[a>>2];case "double":return ia[a>>3];case "*":return G[a>>2];default:I(`invalid type for getValue: ${b}`)}};Module.UTF8ToString=(a,b,c)=>a?ya(E,a,b,c):"";Module.stringToUTF8=(a,b,c)=>S(a,b,c);Module.lengthBytesUTF8=Ga;var Ma,X,Q,V,Ka,U,Na,Y,sa,Oa,B,Ja,Gb={u:a=>{var b=new P(a);z[b.Xa+12]==0&&(z[b.Xa+12]=1,N--);z[b.Xa+
13]=0;K.push(b);return Oa(a)},B:()=>{X(0,0);var a=K.pop();Na(a.Ya);O=null},a:()=>ta([]),k:a=>ta([a]),y:(a,b)=>ta([a,b]),U:()=>{K.length||I("no exception to throw");var a=K.at(-1),b=a.Ya;z[a.Xa+13]=1;z[a.Xa+12]=0;N++;Y(b);O=new x(b);throw O;},_:a=>{if(a){var b=new P(a);z[b.Xa+13]=1;z[b.Xa+12]=0;N++;Y(a);O=new x(a);throw O;}},s:(a,b,c)=>{(new P(a)).init(b,c);Y(a);O=new x(a);N++;throw O;},$:()=>N,f:a=>{O||=new x(a);throw O;},ha:()=>I(""),ga:()=>{J=!1;ua=0},ja:function(a,b){a=a<-9007199254740992||a>9007199254740992?
NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;F[b>>2]=a.getUTCSeconds();F[b+4>>2]=a.getUTCMinutes();F[b+8>>2]=a.getUTCHours();F[b+12>>2]=a.getUTCDate();F[b+16>>2]=a.getUTCMonth();F[b+20>>2]=a.getUTCFullYear()-1900;F[b+24>>2]=a.getUTCDay();F[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;return 0},ka:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();
F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=a.getFullYear();F[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?wa:va)[a.getMonth()]+a.getDate()-1|0;F[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();F[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},ia:function(){},W:(a,b)=>{R[a]&&(clearTimeout(R[a].id),delete R[a]);
if(!b)return 0;var c=setTimeout(()=>{delete R[a];Ba(()=>Ma(a,performance.now()))},b);R[a]={id:c,Za:b};return 0},la:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=Math.max(f,e)*60;F[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(S(a,c,17),S(b,d,17)):(S(a,d,17),S(b,c,17))},na:function(a,b,c){if(!(a>=0&&
a<=3))return 28;H[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},ma:()=>Date.now(),ba:()=>536870912,qa:()=>performance.now(),aa:a=>{var b=E.length;a>>>=0;if(a>536870912)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,Math.ceil(Math.max(a,d)/65536)*65536)-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);fa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},X:(a,b)=>{var c=0,d=0,e;for(e of Fa()){var f=b+
c;G[a+d>>2]=f;c+=S(e,f,Infinity)+1;d+=4}return 0},Y:(a,b)=>{var c=Fa();G[a>>2]=c.length;a=0;for(var d of c)a+=Ga(d)+1;G[b>>2]=a;return 0},ea:()=>52,Z:()=>52,ca:function(){return 70},da:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=G[b>>2],h=G[b+4>>2];b+=8;for(var l=0;l<h;l++){var k=a,t=E[g+l],u=Ha[k];t===0||t===10?((k===1?ea:p)(ya(u)),u.length=0):u.push(t)}e+=h}G[d>>2]=e;return 0},G:Pa,K:Qa,g:Ra,ra:Sa,c:Ta,h:Ua,n:Va,o:Wa,p:Xa,x:Ya,r:Za,S:$a,F:ab,J:bb,T:cb,H:db,N:eb,O:fb,i:gb,b:hb,pa:ib,d:jb,D:kb,M:lb,
L:mb,oa:nb,e:ob,j:pb,m:qb,l:rb,q:sb,t:tb,w:ub,z:vb,V:wb,P:xb,E:yb,sa:zb,R:Ab,C:Bb,I:Cb,A:Db,Q:Eb,ta:Fb,v:a=>a,fa:Aa};function jb(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof v))throw e;X(1,0)}}function Ta(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);if(!(e instanceof v))throw e;X(1,0)}}function Ua(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function rb(a,b,c,d,e,f,g){var h=U();try{T(a)(b,c,d,e,f,g)}catch(l){V(h);if(!(l instanceof
v))throw l;X(1,0)}}function ob(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function hb(a,b){var c=U();try{T(a)(b)}catch(d){V(c);if(!(d instanceof v))throw d;X(1,0)}}function qb(a,b,c,d,e,f){var g=U();try{T(a)(b,c,d,e,f)}catch(h){V(g);if(!(h instanceof v))throw h;X(1,0)}}function Ra(a,b){var c=U();try{return T(a)(b)}catch(d){V(c);if(!(d instanceof v))throw d;X(1,0)}}function Va(a,b,c,d,e){var f=U();try{return T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof v))throw g;
X(1,0)}}function Wa(a,b,c,d,e,f){var g=U();try{return T(a)(b,c,d,e,f)}catch(h){V(g);if(!(h instanceof v))throw h;X(1,0)}}function gb(a){var b=U();try{T(a)()}catch(c){V(b);if(!(c instanceof v))throw c;X(1,0)}}function pb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof v))throw g;X(1,0)}}function Qa(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function Fb(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof v))throw e;
X(1,0)}}function Xa(a,b,c,d,e,f,g){var h=U();try{return T(a)(b,c,d,e,f,g)}catch(l){V(h);if(!(l instanceof v))throw l;X(1,0)}}function wb(a,b,c,d,e,f,g,h,l,k,t,u){var w=U();try{T(a)(b,c,d,e,f,g,h,l,k,t,u)}catch(y){V(w);if(!(y instanceof v))throw y;X(1,0)}}function vb(a,b,c,d,e,f,g,h,l,k,t){var u=U();try{T(a)(b,c,d,e,f,g,h,l,k,t)}catch(w){V(u);if(!(w instanceof v))throw w;X(1,0)}}function Bb(a,b,c,d,e,f){var g=U();try{T(a)(b,c,d,e,f)}catch(h){V(g);if(!(h instanceof v))throw h;X(1,0)}}function Cb(a,
b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof v))throw g;X(1,0)}}function Ya(a,b,c,d,e,f,g,h){var l=U();try{return T(a)(b,c,d,e,f,g,h)}catch(k){V(l);if(!(k instanceof v))throw k;X(1,0)}}function sb(a,b,c,d,e,f,g,h){var l=U();try{T(a)(b,c,d,e,f,g,h)}catch(k){V(l);if(!(k instanceof v))throw k;X(1,0)}}function db(a,b,c,d,e,f,g){var h=U();try{return T(a)(b,c,d,e,f,g)}catch(l){V(h);if(!(l instanceof v))throw l;X(1,0)}}function Za(a,b,c,d,e,f,g,h,l){var k=U();try{return T(a)(b,c,
d,e,f,g,h,l)}catch(t){V(k);if(!(t instanceof v))throw t;X(1,0)}}function tb(a,b,c,d,e,f,g,h,l){var k=U();try{T(a)(b,c,d,e,f,g,h,l)}catch(t){V(k);if(!(t instanceof v))throw t;X(1,0)}}function ub(a,b,c,d,e,f,g,h,l,k){var t=U();try{T(a)(b,c,d,e,f,g,h,l,k)}catch(u){V(t);if(!(u instanceof v))throw u;X(1,0)}}function zb(a,b,c,d,e,f,g,h,l,k,t,u,w,y,A,L,M){var D=U();try{T(a)(b,c,d,e,f,g,h,l,k,t,u,w,y,A,L,M)}catch(Ea){V(D);if(!(Ea instanceof v))throw Ea;X(1,0)}}function Pa(a){var b=U();try{return T(a)()}catch(c){V(b);
if(!(c instanceof v))throw c;X(1,0)}}function cb(a,b,c,d,e,f,g,h,l,k,t,u,w,y,A,L){var M=U();try{return T(a)(b,c,d,e,f,g,h,l,k,t,u,w,y,A,L)}catch(D){V(M);if(!(D instanceof v))throw D;X(1,0)}}function bb(a,b,c,d,e,f,g,h,l,k,t,u,w){var y=U();try{return T(a)(b,c,d,e,f,g,h,l,k,t,u,w)}catch(A){V(y);if(!(A instanceof v))throw A;X(1,0)}}function $a(a,b,c,d,e,f,g,h,l,k,t){var u=U();try{return T(a)(b,c,d,e,f,g,h,l,k,t)}catch(w){V(u);if(!(w instanceof v))throw w;X(1,0)}}function Ab(a,b,c,d,e,f,g,h,l){var k=
U();try{T(a)(b,c,d,e,f,g,h,l)}catch(t){V(k);if(!(t instanceof v))throw t;X(1,0)}}function Eb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof v))throw g;X(1,0)}}function xb(a,b,c,d,e,f,g,h,l,k,t,u,w){var y=U();try{T(a)(b,c,d,e,f,g,h,l,k,t,u,w)}catch(A){V(y);if(!(A instanceof v))throw A;X(1,0)}}function fb(a,b,c,d,e,f){var g=U();try{return T(a)(b,c,d,e,f)}catch(h){V(g);if(!(h instanceof v))throw h;X(1,0);return 0n}}function Sa(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);
if(!(e instanceof v))throw e;X(1,0)}}function eb(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);if(!(e instanceof v))throw e;X(1,0)}}function ib(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof v))throw e;X(1,0)}}function kb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function Db(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function lb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof
v))throw g;X(1,0)}}function mb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof v))throw f;X(1,0)}}function nb(a,b,c,d,e,f,g){var h=U();try{T(a)(b,c,d,e,f,g)}catch(l){V(h);if(!(l instanceof v))throw l;X(1,0)}}function ab(a,b,c,d,e,f,g,h,l,k,t,u){var w=U();try{return T(a)(b,c,d,e,f,g,h,l,k,t,u)}catch(y){V(w);if(!(y instanceof v))throw y;X(1,0)}}function yb(a,b,c,d,e,f,g,h,l,k,t,u,w,y,A,L){var M=U();try{T(a)(b,c,d,e,f,g,h,l,k,t,u,w,y,A,L)}catch(D){V(M);if(!(D instanceof v))throw D;
X(1,0)}}var Z;Z=await (async function(){function a(d){d=Z=d.exports;Module._luau_add_module=d.wa;Module._luau_clear_modules=d.xa;Module._luau_get_modules=d.ya;Module._luau_execute=d.za;Module._free=d.Aa;Module._luau_dump_bytecode=d.Ca;Module._luau_set_mode=d.Da;Module._luau_set_solver=d.Ea;Module._luau_set_fflags=d.Fa;Module._luau_set_source=d.Ga;Module._luau_clear_sources=d.Ha;Module._luau_get_diagnostics=d.Ia;Module._luau_autocomplete=d.Ja;Module._luau_hover=d.Ka;Module._luau_signature_help=
d.La;Module._malloc=d.Ma;Ma=d.Na;X=d.Oa;Q=d.Pa;V=d.Qa;Ka=d.Ra;U=d.Sa;Na=d.Ta;Y=d.Ua;sa=d.Va;Oa=d.Wa;B=d.ua;Ja=d.Ba;fa();return Z}var b={a:Gb},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});na??=Module.locateFile?Module.locateFile?Module.locateFile("luau.wasm",m):m+"luau.wasm":(new URL(/* @vite-ignore */ "luau.wasm",import.meta.url)).href;return function(d){return a(d.instance)}(await qa(b))}());await (async function(){ja();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>
setTimeout(b,1)),setTimeout(a,1,""));q||(Z.va(),Module.onRuntimeInitialized?.(),la())}());;return Module}export default createLuauModule;
