// @ts-nocheck
async function createLuauModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.WorkerGlobalScope,ba="./this.program",ca=import.meta.url,n="",da,p;if(globalThis.window||aa){try{n=(new URL(".",ca)).href}catch{}aa&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ea=console.log.bind(console),q=console.error.bind(console),r,t=!1,w;
class y{}class z extends y{constructor(a){super();this.Ua=a}}var fa,ha,ia=!1;function ja(){var a=B.buffer;D=new Int8Array(a);E=new Int16Array(a);F=new Uint8Array(a);new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);ka=new Float32Array(a);ma=new Float64Array(a);J=new BigInt64Array(a);new BigUint64Array(a)}function K(a){h.onAbort?.(a);a=`Aborted(${a})`;q(a);t=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var na;
async function oa(a){if(!r)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==na&&r)a=new Uint8Array(r);else if(p)a=p(a);else throw"both async and sync fetching of the wasm failed";return a}async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),K(d)}}
async function qa(a){var b=na;if(!r)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var E,H,J,D,ka,ma,I,F,sa=a=>{for(;0<a.length;)a.shift()(h)},ta=[],ua=[],va=()=>{var a=h.preRun.shift();ua.push(a)},L=!0,M=[],N=0,O=null;
class P{constructor(a){this.Ua=a;this.Ta=a-24}}
var xa=a=>{var b=O?.Ua;if(!b)return Q(0),0;var c=new P(b);I[c.Ta+16>>2]=b;var d=I[c.Ta+4>>2];if(!d)return Q(0),b;for(var e of a){if(0===e||e===d)break;if(wa(e,d,c.Ta+16))return Q(e),b}Q(d);return b},ya=0,za=[0,31,60,91,121,152,182,213,244,274,305,335],Aa=[0,31,59,90,120,151,181,212,243,273,304,334],Ba=globalThis.TextDecoder&&new TextDecoder,Ca=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(16<d-b&&a.buffer&&Ba)return Ba.decode(a.subarray(b,d));for(e="";b<d;)if(c=a[b++],c&
128){var f=a[b++]&63;if(192==(c&224))e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=224==(c&240)?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;65536>c?e+=String.fromCharCode(c):(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},R={},Da=a=>{if(!(a instanceof ra||"unwind"==a))throw a;},Ea=a=>{w=a;L||0<ya||(h.onExit?.(a),t=!0);throw new ra(a);},Fa=a=>{if(!t)try{a()}catch(b){Da(b)}finally{if(!(L||0<ya))try{w=a=w,Ea(a)}catch(b){Da(b)}}},
S=(a,b,c)=>{var d=F;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Ga={},Ia=()=>{if(!Ha){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Ga)void 0===Ga[b]?delete a[b]:a[b]=Ga[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ha=c}return Ha},Ha,Ka=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},La=[null,[],[]],Ma=[],T=a=>{var b=Ma[a];b||(Ma[a]=b=Na.get(a));return b},Pa=(a,b,c,d)=>{var e={string:l=>{var u=0;if(null!==l&&void 0!==l&&0!==l){u=Ka(l)+1;var v=Oa(u);
S(l,v,u);u=v}return u},array:l=>{var u=Oa(l.length);D.set(l,u);return u}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===g&&(g=V()),f[k]=m(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==g&&W(g);return"string"===b?l?Ca(F,l):"":"boolean"===b?!!l:l}(c)};h.noExitRuntime&&(L=h.noExitRuntime);h.print&&(ea=h.print);h.printErr&&(q=h.printErr);h.wasmBinary&&(r=h.wasmBinary);h.thisProgram&&(ba=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Pa;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Pa(a,b,c,f,d)};
h.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":D[a]=b;break;case "i8":D[a]=b;break;case "i16":E[a>>1]=b;break;case "i32":H[a>>2]=b;break;case "i64":J[a>>3]=BigInt(b);break;case "float":ka[a>>2]=b;break;case "double":ma[a>>3]=b;break;case "*":I[a>>2]=b;break;default:K(`invalid type for setValue: ${c}`)}};
h.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return D[a];case "i8":return D[a];case "i16":return E[a>>1];case "i32":return H[a>>2];case "i64":return J[a>>3];case "float":return ka[a>>2];case "double":return ma[a>>3];case "*":return I[a>>2];default:K(`invalid type for getValue: ${b}`)}};h.UTF8ToString=(a,b,c)=>a?Ca(F,a,b,c):"";h.stringToUTF8=(a,b,c)=>S(a,b,c);h.lengthBytesUTF8=Ka;
var Qa,X,Q,W,Oa,V,Ra,Y,wa,Sa,B,Na,Jb={u:a=>{var b=new P(a);0==D[b.Ta+12]&&(D[b.Ta+12]=1,N--);D[b.Ta+13]=0;M.push(b);return Sa(a)},B:()=>{X(0,0);var a=M.pop();Ra(a.Ua);O=null},a:()=>xa([]),k:a=>xa([a]),x:(a,b)=>xa([a,b]),R:()=>{M.length||K("no exception to throw");var a=M.at(-1),b=a.Ua;D[a.Ta+13]=1;D[a.Ta+12]=0;N++;Y(b);O=new z(b);throw O;},W:a=>{if(a){var b=new P(a);D[b.Ta+13]=1;D[b.Ta+12]=0;N++;Y(a);O=new z(a);throw O;}},t:(a,b,c)=>{var d=new P(a);I[d.Ta+16>>2]=0;I[d.Ta+4>>2]=b;I[d.Ta+8>>2]=c;Y(a);
O=new z(a);N++;throw O;},X:()=>N,f:a=>{O||=new z(a);throw O;},ba:()=>K(""),aa:()=>{L=!1;ya=0},da:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);H[b>>2]=a.getUTCSeconds();H[b+4>>2]=a.getUTCMinutes();H[b+8>>2]=a.getUTCHours();H[b+12>>2]=a.getUTCDate();H[b+16>>2]=a.getUTCMonth();H[b+20>>2]=a.getUTCFullYear()-1900;H[b+24>>2]=a.getUTCDay();H[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},ea:function(a,b){a=-9007199254740992>a||9007199254740992<
a?NaN:Number(a);a=new Date(1E3*a);H[b>>2]=a.getSeconds();H[b+4>>2]=a.getMinutes();H[b+8>>2]=a.getHours();H[b+12>>2]=a.getDate();H[b+16>>2]=a.getMonth();H[b+20>>2]=a.getFullYear()-1900;H[b+24>>2]=a.getDay();var c=a.getFullYear();H[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Aa:za)[a.getMonth()]+a.getDate()-1|0;H[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();H[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,
c))|0},ca:function(){},T:(a,b)=>{R[a]&&(clearTimeout(R[a].id),delete R[a]);if(!b)return 0;var c=setTimeout(()=>{delete R[a];Fa(()=>Qa(a,performance.now()))},b);R[a]={id:c,Va:b};return 0},fa:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();I[a>>2]=60*Math.max(f,e);H[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<
f?(S(a,c,17),S(b,d,17)):(S(a,d,17),S(b,c,17))},ha:function(a,b,c){if(!(0<=a&&3>=a))return 28;J[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},ga:()=>Date.now(),Z:()=>536870912,ka:()=>performance.now(),Y:a=>{var b=F.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
U:(a,b)=>{var c=0,d=0,e;for(e of Ia()){var f=b+c;I[a+d>>2]=f;c+=S(e,f,Infinity)+1;d+=4}return 0},V:(a,b)=>{var c=Ia();I[a>>2]=c.length;a=0;for(var d of c)a+=Ka(d)+1;I[b>>2]=a;return 0},_:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=I[b>>2],k=I[b+4>>2];b+=8;for(var m=0;m<k;m++){var l=a,u=F[g+m],v=La[l];0===u||10===u?((1===l?ea:q)(Ca(v)),v.length=0):v.push(u)}e+=k}I[d>>2]=e;return 0},K:Ta,L:Ua,g:Va,G:Wa,c:Xa,h:Ya,n:Za,o:$a,p:ab,y:bb,r:cb,J:db,F:eb,ma:fb,na:gb,H:hb,O:ib,la:jb,j:kb,b:lb,ja:mb,d:nb,D:ob,
N:pb,M:qb,ia:rb,e:sb,i:tb,m:ub,l:vb,q:wb,s:xb,w:yb,z:zb,S:Ab,E:Bb,oa:Cb,Q:Db,C:Eb,I:Fb,A:Gb,P:Hb,pa:Ib,v:a=>a,$:Ea};function nb(a,b,c){var d=V();try{T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}function Xa(a,b,c){var d=V();try{return T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}function Ya(a,b,c,d){var e=V();try{return T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}
function vb(a,b,c,d,e,f,g){var k=V();try{T(a)(b,c,d,e,f,g)}catch(m){W(k);if(!(m instanceof y))throw m;X(1,0)}}function sb(a,b,c,d){var e=V();try{T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}function lb(a,b){var c=V();try{T(a)(b)}catch(d){W(c);if(!(d instanceof y))throw d;X(1,0)}}function ub(a,b,c,d,e,f){var g=V();try{T(a)(b,c,d,e,f)}catch(k){W(g);if(!(k instanceof y))throw k;X(1,0)}}
function Va(a,b){var c=V();try{return T(a)(b)}catch(d){W(c);if(!(d instanceof y))throw d;X(1,0)}}function Za(a,b,c,d,e){var f=V();try{return T(a)(b,c,d,e)}catch(g){W(f);if(!(g instanceof y))throw g;X(1,0)}}function $a(a,b,c,d,e,f){var g=V();try{return T(a)(b,c,d,e,f)}catch(k){W(g);if(!(k instanceof y))throw k;X(1,0)}}function kb(a){var b=V();try{T(a)()}catch(c){W(b);if(!(c instanceof y))throw c;X(1,0)}}
function tb(a,b,c,d,e){var f=V();try{T(a)(b,c,d,e)}catch(g){W(f);if(!(g instanceof y))throw g;X(1,0)}}function Ua(a,b,c,d){var e=V();try{return T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}function Ib(a,b,c){var d=V();try{T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}function ab(a,b,c,d,e,f,g){var k=V();try{return T(a)(b,c,d,e,f,g)}catch(m){W(k);if(!(m instanceof y))throw m;X(1,0)}}
function Ab(a,b,c,d,e,f,g,k,m,l,u,v){var x=V();try{T(a)(b,c,d,e,f,g,k,m,l,u,v)}catch(A){W(x);if(!(A instanceof y))throw A;X(1,0)}}function zb(a,b,c,d,e,f,g,k,m,l,u){var v=V();try{T(a)(b,c,d,e,f,g,k,m,l,u)}catch(x){W(v);if(!(x instanceof y))throw x;X(1,0)}}function Eb(a,b,c,d,e,f){var g=V();try{T(a)(b,c,d,e,f)}catch(k){W(g);if(!(k instanceof y))throw k;X(1,0)}}function Fb(a,b,c,d,e){var f=V();try{T(a)(b,c,d,e)}catch(g){W(f);if(!(g instanceof y))throw g;X(1,0)}}
function bb(a,b,c,d,e,f,g,k){var m=V();try{return T(a)(b,c,d,e,f,g,k)}catch(l){W(m);if(!(l instanceof y))throw l;X(1,0)}}function wb(a,b,c,d,e,f,g,k){var m=V();try{T(a)(b,c,d,e,f,g,k)}catch(l){W(m);if(!(l instanceof y))throw l;X(1,0)}}function hb(a,b,c,d,e,f,g){var k=V();try{return T(a)(b,c,d,e,f,g)}catch(m){W(k);if(!(m instanceof y))throw m;X(1,0)}}function cb(a,b,c,d,e,f,g,k,m){var l=V();try{return T(a)(b,c,d,e,f,g,k,m)}catch(u){W(l);if(!(u instanceof y))throw u;X(1,0)}}
function xb(a,b,c,d,e,f,g,k,m){var l=V();try{T(a)(b,c,d,e,f,g,k,m)}catch(u){W(l);if(!(u instanceof y))throw u;X(1,0)}}function yb(a,b,c,d,e,f,g,k,m,l){var u=V();try{T(a)(b,c,d,e,f,g,k,m,l)}catch(v){W(u);if(!(v instanceof y))throw v;X(1,0)}}function Cb(a,b,c,d,e,f,g,k,m,l,u,v,x,A,C,G,la){var U=V();try{T(a)(b,c,d,e,f,g,k,m,l,u,v,x,A,C,G,la)}catch(Ja){W(U);if(!(Ja instanceof y))throw Ja;X(1,0)}}function Ta(a){var b=V();try{return T(a)()}catch(c){W(b);if(!(c instanceof y))throw c;X(1,0)}}
function gb(a,b,c,d,e,f,g,k,m,l,u,v,x,A){var C=V();try{return T(a)(b,c,d,e,f,g,k,m,l,u,v,x,A)}catch(G){W(C);if(!(G instanceof y))throw G;X(1,0)}}function db(a,b,c,d,e,f,g,k,m,l,u){var v=V();try{return T(a)(b,c,d,e,f,g,k,m,l,u)}catch(x){W(v);if(!(x instanceof y))throw x;X(1,0)}}function Db(a,b,c,d,e,f,g,k,m){var l=V();try{T(a)(b,c,d,e,f,g,k,m)}catch(u){W(l);if(!(u instanceof y))throw u;X(1,0)}}
function fb(a,b,c,d,e,f,g,k,m,l,u,v,x){var A=V();try{return T(a)(b,c,d,e,f,g,k,m,l,u,v,x)}catch(C){W(A);if(!(C instanceof y))throw C;X(1,0)}}function Hb(a,b,c,d,e){var f=V();try{T(a)(b,c,d,e)}catch(g){W(f);if(!(g instanceof y))throw g;X(1,0)}}function jb(a,b,c,d,e,f){var g=V();try{return T(a)(b,c,d,e,f)}catch(k){W(g);if(!(k instanceof y))throw k;X(1,0);return 0n}}function Wa(a,b,c){var d=V();try{return T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}
function ib(a,b,c){var d=V();try{return T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}function mb(a,b,c){var d=V();try{T(a)(b,c)}catch(e){W(d);if(!(e instanceof y))throw e;X(1,0)}}function ob(a,b,c,d){var e=V();try{T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}function Gb(a,b,c,d){var e=V();try{T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}function pb(a,b,c,d,e){var f=V();try{T(a)(b,c,d,e)}catch(g){W(f);if(!(g instanceof y))throw g;X(1,0)}}
function qb(a,b,c,d){var e=V();try{T(a)(b,c,d)}catch(f){W(e);if(!(f instanceof y))throw f;X(1,0)}}function rb(a,b,c,d,e,f,g){var k=V();try{T(a)(b,c,d,e,f,g)}catch(m){W(k);if(!(m instanceof y))throw m;X(1,0)}}function eb(a,b,c,d,e,f,g,k,m,l,u,v){var x=V();try{return T(a)(b,c,d,e,f,g,k,m,l,u,v)}catch(A){W(x);if(!(A instanceof y))throw A;X(1,0)}}function Bb(a,b,c,d,e,f,g,k,m,l,u,v,x,A,C,G){var la=V();try{T(a)(b,c,d,e,f,g,k,m,l,u,v,x,A,C,G)}catch(U){W(la);if(!(U instanceof y))throw U;X(1,0)}}var Z;
Z=await (async function(){function a(c){c=Z=c.exports;h._luau_add_module=c.sa;h._luau_clear_modules=c.ta;h._luau_get_modules=c.ua;h._luau_execute=c.va;h._free=c.wa;h._luau_dump_bytecode=c.ya;h._luau_set_mode=c.za;h._luau_set_solver=c.Aa;h._luau_set_fflags=c.Ba;h._luau_set_source=c.Ca;h._luau_clear_sources=c.Da;h._luau_get_diagnostics=c.Ea;h._luau_autocomplete=c.Fa;h._luau_hover=c.Ga;h._luau_signature_help=c.Ha;h._malloc=c.Ia;Qa=c.Ja;X=c.Ka;Q=c.La;W=c.Ma;Oa=c.Na;V=c.Oa;Ra=c.Pa;Y=c.Qa;wa=
c.Ra;Sa=c.Sa;B=c.qa;Na=c.xa;ja();return Z}var b={a:Jb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});na??=h.locateFile?h.locateFile?h.locateFile("luau.wasm",n):n+"luau.wasm":(new URL(/* @vite-ignore */ "luau.wasm",import.meta.url)).href;return a((await qa(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!t){ia=!0;Z.ra();fa?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ta.push(b)}sa(ta)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();sa(ua);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ia?moduleRtn=h:moduleRtn=new Promise((a,b)=>{fa=a;ha=b});
;return moduleRtn}export default createLuauModule;
